# Generated by Django 4.0.5 on 2022-06-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False, verbose_name='Rut de cliente')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre de cliente')),
                ('apellido', models.CharField(max_length=25, verbose_name='Apellido de cliente')),
                ('email', models.CharField(max_length=50, verbose_name='Email de cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Producto')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de producto')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca de producto')),
                ('fechaFabricacion', models.DateField()),
            ],
        ),
    ]
