# Generated by Django 4.0.5 on 2022-06-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MascotasCore', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=25, null=True, verbose_name='Direccion de cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(null=True, verbose_name='Telefono de cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Rut de cliente'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Productos'),
        ),
    ]
